//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMTLicenseManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMTLicenseManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;txyAkgkMRnNRkPHoIrOzRPFN+0P58WhpkYGN6ao4hqPvkFy1aBGlP81IhL2Ayjfyo7Gh9/PNPuWGO2Vncm8oxvXg9zP8tszK3+CThr1QlLDufHd+1tGi+CfYMxjDCDqM4PBCPkhupKNzG1PI8NsKMwOTqYy6IxyRUBPvNlNdwHU=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;2XmSqLKUeETCSwyqICjHgFPnXoogZfZsAPzj3oc771GK3Pvt+VzgthoVjbxX4WvIt2jGPjRiTMf0Lc7iLUuIzw==&lt;/P&gt;&lt;Q&gt;14yNKD+cw9N0KpQ8dPw0yNT4N0xGvly5IM2whIw+FC2pCHUpUNgL0XCv2Djrmp73A8w097v2H4fpdE4kE/Prew==&lt;/Q&gt;&lt;DP&gt;Uhe9T+cRepDiEvh14+vg20VQ6nQTpMmvnXPZBLBh5IYQeDi1bVMtFDCmgDlfpx1LyEhJxUN68+bq+rvEzzpbKw==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;txyAkgkMRnNRkPHoIrOzRPFN+0P58WhpkYGN6ao4hqPvkFy1aBGlP81IhL2Ayjfyo7Gh9/PNPuWGO2Vncm8oxvXg9zP8tszK3+CThr1QlLDufHd+1tGi+CfYMxjDCDqM4PBCPkhupKNzG1PI8NsKMwOTqYy6IxyRUBPvNlNdwHU=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
    }
}
